# Generated by Django 5.2.6 on 2026-07-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promyvki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntifreezeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('antifreeze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.antifreeze')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.compressorstation')),
            ],
            options={
                'unique_together': {('station', 'antifreeze')},
            },
        ),
        migrations.CreateModel(
            name='CleaningFluidBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fluid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.cleaningfluid')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.compressorstation')),
            ],
            options={
                'unique_together': {('station', 'fluid')},
            },
        ),
    ]
