# Generated by Django 5.2.6 on 2026-07-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
        ('promyvki', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cleaningfluidbalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cleaningfluidbalance',
            name='fluid',
        ),
        migrations.RemoveField(
            model_name='cleaningfluidbalance',
            name='station',
        ),
        migrations.CreateModel(
            name='MaterialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество (л)')),
                ('cleaning_fluid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.cleaningfluid', verbose_name='Промывочная жидкость')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.compressorstation', verbose_name='Компрессорная станция')),
            ],
            options={
                'verbose_name': 'Материальный баланс',
                'verbose_name_plural': 'Материальный баланс',
            },
        ),
        migrations.DeleteModel(
            name='AntifreezeBalance',
        ),
        migrations.DeleteModel(
            name='CleaningFluidBalance',
        ),
    ]
