# Generated by Django 5.2.6 on 2026-07-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_cleaningfluidbalance_unique_together_and_more'),
        ('promyvki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('arrival', 'Приход'), ('writeoff', 'Списание'), ('transfer_out', 'Передача другой КС'), ('transfer_in', 'Получение от другой КС')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество (л)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('cleaning_fluid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.cleaningfluid', verbose_name='Промывочная жидкость')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.compressorstation', verbose_name='Компрессорная станция')),
            ],
            options={
                'verbose_name': 'Операция с материалом',
                'verbose_name_plural': 'Операции с материалами',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='MaterialBalance',
        ),
    ]
