# Generated by Django 5.2.6 on 2026-07-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0003_materialoperation_delete_materialbalance'),
        ('promyvki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialoperation',
            options={'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.RemoveField(
            model_name='materialoperation',
            name='station',
        ),
        migrations.AddField(
            model_name='materialoperation',
            name='from_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='promyvki.compressorstation', verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='materialoperation',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='promyvki.compressorstation', verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='materialoperation',
            name='operation_type',
            field=models.CharField(choices=[('arrival', 'Приход'), ('writeoff', 'Списание'), ('transfer', 'Перераспределение')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
