# Generated by Django 5.2.6 on 2026-07-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_materialoperation_material_support'),
        ('promyvki', '0003_alter_antifreeze_options_alter_cleaningfluid_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialoperation',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Операция с материалом', 'verbose_name_plural': 'Операции с материалами'},
        ),
        migrations.AlterField(
            model_name='materialoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество (л)'),
        ),
        migrations.AlterField(
            model_name='materialoperation',
            name='from_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_from', to='promyvki.compressorstation', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='materialoperation',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_to', to='promyvki.compressorstation', verbose_name='Куда'),
        ),
    ]
