# Generated by Django 5.2.6 on 2026-07-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antifreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Антифриз')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningFluid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Промывочная жидкость')),
            ],
        ),
        migrations.CreateModel(
            name='CompressorStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название КС')),
            ],
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата промывки')),
                ('kts_before', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='КТС до промывки')),
                ('kts_after', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='КТС после промывки')),
                ('cleaning_fluid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расход жидкости (л)')),
                ('antifreeze_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расход антифриза (л)')),
                ('antifreeze', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promyvki.antifreeze')),
                ('cleaning_fluid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promyvki.cleaningfluid')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promyvki.compressorstation', verbose_name='Компрессорная станция')),
            ],
        ),
    ]
