# Generated by Django 5.2.6 on 2026-07-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promyvki', '0002_wash_created_by_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antifreeze',
            options={'ordering': ['name'], 'verbose_name': 'Антифриз', 'verbose_name_plural': 'Антифризы'},
        ),
        migrations.AlterModelOptions(
            name='cleaningfluid',
            options={'ordering': ['name'], 'verbose_name': 'Промывочная жидкость', 'verbose_name_plural': 'Промывочные жидкости'},
        ),
        migrations.AlterModelOptions(
            name='compressorstation',
            options={'ordering': ['name'], 'verbose_name': 'Компрессорная станция', 'verbose_name_plural': 'Компрессорные станции'},
        ),
        migrations.AlterModelOptions(
            name='wash',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Промывка', 'verbose_name_plural': 'Промывки'},
        ),
        migrations.AlterField(
            model_name='wash',
            name='antifreeze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promyvki.antifreeze', verbose_name='Антифриз'),
        ),
        migrations.AlterField(
            model_name='wash',
            name='antifreeze_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расход антифриза (л)'),
        ),
        migrations.AlterField(
            model_name='wash',
            name='cleaning_fluid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promyvki.cleaningfluid', verbose_name='Промывочная жидкость'),
        ),
        migrations.AlterField(
            model_name='wash',
            name='cleaning_fluid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Расход жидкости (л)'),
        ),
    ]
